# Generated by Django 6.0.6 on 2026-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('article_class', models.IntegerField(default=0)),
                ('article_class_name', models.CharField(max_length=100)),
                ('num_of_comments', models.IntegerField(default=0)),
                ('num_of_shares', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('picture_path', models.CharField(blank=True, max_length=500)),
                ('corpus_index', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['corpus_index'],
            },
        ),
        migrations.CreateModel(
            name='ResourceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('US', 'United States'), ('WE', 'Western Europe')], max_length=2)),
                ('phrase', models.CharField(max_length=100)),
                ('expansion_terms', models.CharField(blank=True, help_text='Bosnian expansion terms appended to the query vector.', max_length=300)),
            ],
            options={
                'ordering': ['region', 'phrase'],
                'unique_together': {('region', 'phrase')},
            },
        ),
    ]
