# Generated by Django 6.0.6 on 2026-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
