# Generated by Django 6.0.6 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_article_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('article_idx', models.IntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'unique_together': {('session_key', 'article_idx')},
            },
        ),
    ]
